### ISSUE TITLE
Windows 10 UAP platform project not working

### ISSUE THREAD

**Issue by uzyfeo** [mono/MonoGame#4037] opened 2015-07-30 19:04 UTC
I upgraded today to Windows 10 and Visual Studio 2015 Community Edition and latest build of Monogame downloaded from TeamCity. I was interested in Windows 10 universal apps and wanted to try It out...

Unfortunately, when I tried to create new project with Windows 10 UAP target platform, error showed up which is described here: https://msdn.microsoft.com/en-us/library/windows/apps/xaml/mt188198.aspx
(it was also a link which the error produced).

I try to run it with this workaround but this looks like some serious incompatibility.

**Comment by tomspilman** [comment] 2015-07-30 19:49
We're working on this over in https://github.com/mono/MonoGame/pull/4031.  It should be fixed soon.

**Comment by Amimox** [comment] 2015-08-01 01:08
When?

**Comment by Nezz** [comment] 2015-08-02 22:11
@tomspilman Can we close this?

**Comment by tomspilman** [comment] 2015-08-02 22:41
Sure... if someone has other specific issues we can address them separately.

**Closed by tomspilman** 2015-08-02 22:41 UTC

**Comment by bsimser** [comment] 2015-12-30 23:01
Would like to re-open this. As of MonoGame 3.4 this isn't working with the RTM version of the UAP SDK on Windows 10. I just cleaned up my system (I had an old version kicking around) and re-installed the one from the MSDN site. It dropped files in C:\Program Files (x86)\Windows Kits\10\Platforms\UAP\10.0.10586.0 but the generated .csproj file references this version:

<TargetPlatformVersion>10.0.10069.0</TargetPlatformVersion>
<TargetPlatformMinVersion>10.0.10069.0</TargetPlatformMinVersion>

Changing the values manually worked and loaded the project (had to restart Visual Studio and recompile).

This is with Visual Studio 2015 version 14.0.24720.00 Update 1 and the current version of the UAP SDK downloaded from here: https://dev.windows.com/en-us/downloads/windows-10-sdk

**Comment by tomspilman** [comment] 2015-12-31 03:27
> As of MonoGame 3.4 this isn't working 

The fix was done to the current development build for MonoGame 3.5.  You can try the latest development build by downloading the installer from here:

http://www.monogame.net/downloads/

**Comment by bsimser** [comment] 2015-12-31 16:28
Okay, confirmed that 3.5 has the right zip name, project.json file, and .csproj values are correct. Most people might not be downloading the development builds so anyone with problems on WIndows 10 and UAP should know about this.

**Comment by DDReaper** [comment] 2015-12-31 19:06
Best to probably put a note on the downloads page not to use 3.4 for Windows 10 development since it's no longer functional.
