### ISSUE TITLE
GameHasControl always returns true on iOS regardless of background music.

### ISSUE THREAD

**Issue by vchelaru** [mono/MonoGame#4185] opened 2015-10-18 20:10 UTC
To reproduce:

1. Create a MonoGame iOS project
1. Open Spotify
1. Begin playing music on spotify
1. Run the game
1. Check ```Microsoft.Xna.Framework.Media.MediaPlayer.GameHasControl```

Expected: ```Microsoft.Xna.Framework.Media.MediaPlayer.GameHasControl``` should return false if background music is playing
Actual results: ```Microsoft.Xna.Framework.Media.MediaPlayer.GameHasControl``` returns true regardless of whether background music is playing.

**Comment by vchelaru** [comment] 2015-10-18 20:21
On further research it seems like launching the monogame game stops background music from playing - so the property may actually be correct, but there's something else going on here. I'll update as I find more...

**Comment by vchelaru** [comment] 2015-10-18 20:28
There seems to be something else going on with audio automatically stopping.

**Comment by danzel** [comment] 2015-10-18 20:29
Dupe of #735 ?

**Closed** 2015-10-18 20:28 UTC
Labels: iOS

**Comment by vchelaru** [comment] 2015-10-18 20:59
Thanks @danzel , that is indeed it, and seems to have died at the beginning of 2013.
