### ISSUE TITLE
Replace MGFX DirectX Preprocessor With Portable One

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#1972] opened 2013-09-05 22:46 UTC
Currently the MGFX tools depend on the Microsoft DirectX Preprocessor API for resolving `#include`s, `#define`s, and such before the shader is compiled.

https://github.com/mono/MonoGame/blob/develop/Tools/2MGFX/ShaderInfo.cs#L400

We need to replace this preprocessor with one of our own that is portable to Mac and Linux and does not have a dependency on DirectX.

**Comment by tomspilman** [comment] 2015-03-17 15:29
Anyone have time to take a look at this?  The work to be done:

  1. Compile an AnyCPU version of  [CppNet](https://github.com/xtravar/CppNet) and add it to [MonoGame-Dependencies](https://github.com/Mono-Game/MonoGame.Dependencies).
  2. Replace the call to [`SharpDX.D3DCompiler.ShaderBytecode.Preprocess`](https://github.com/mono/MonoGame/blob/develop/Tools/2MGFX/ShaderInfo.cs#L70) with CppNet.
  3. Make sure it generates equivalent pre-processed source files as before.

This then opens us up for the next steps towards supporting GLSL FX files.

**Comment by tgjones** [comment] 2015-03-24 10:28
I'll take a look at this. I'm already using CppNet for my own project, so it shouldn't take too long to get up and running for MonoGame.

**Comment by tgjones** [comment] 2015-03-24 13:13
First step - https://github.com/xtravar/CppNet/pull/2 - modify CppNet to allow us to grab all the warnings and errors, instead of an exception being thrown after the first error.

**Comment by tgjones** [comment] 2015-03-24 14:22
I have this working locally - calling CppNet from `ShaderInfo` instead of D3D's preprocessor. I'll wait until my CppNet pull request is merged, and then proceed from there.

Because 2MGFX doesn't reference the MG content pipeline assembly, it doesn't have access to `ContentProcessorContext` or `ContentIdentity`, so it's difficult to properly handle warnings and errors. I think the MGFX parser faces this same difficulty.

At the moment, I'm ignoring preprocessor warnings, and throwing an exception for the first preprocessor error. But it would be much nicer if we could pass the line and column numbers back to the content pipeline so that errors are clickable.

**Comment by tomspilman** [comment] 2015-03-25 20:57
> Because 2MGFX doesn't reference the MG content pipeline assembly, it doesn't have access to  `ContentProcessorContext` or `ContentIdentity`, so it's difficult to properly handle warnings and errors.

The reason is the monolithic nature of content pipeline assembly.  It would the 2MGFX tool would include assemblies for texture processing for instance when it doesn't require it.  This is also why 2MGFX links the code to some MonoGame.Framework classes and doesn't link against the assembly.

The "right" fix would be to break up the pipeline and framework assemblies a bit more.

> At the moment, I'm ignoring preprocessor warnings, and throwing an exception for the first preprocessor error.

Might want to see what we do with the HLSL compiler errors.  It might be a good way to handle the preprocessor output too.

**Comment by tomspilman** [comment] 2015-03-25 21:01
> it would be much nicer if we could pass the line and column numbers back to the content pipeline so that errors are clickable.

Just thinking... maybe we flip things around?  We add this to the 2MGFX code:

```
interface IEffectCompilerOutput
{
   void WriteWarning(string file, int line, string message);
   void WriteError(string file, int line, string message);
}
```
We have to pass this interface to the 2MGFX processing methods and it replaces its normal logging.  Within the `EffectProcessor` in the pipeline it writes a handler for this interface which redirects to the pipeline output methods.

**Comment by tgjones** [comment] 2015-03-26 14:08
> Just thinking... maybe we flip things around?

Yeah, that's a nice idea - I've done it that way.

**Closed** 2015-04-03 16:04 UTC
Labels: Help Wanted, Linux, MacOS, MGFX, Windows

**Comment by soenneker** [comment] 2015-05-01 00:41
Hello,

Using the 3.4 pipeline tool, I'm getting the following error: Shared.fx: error X3000: syntax error: unexpected token '#'. The #include preprocessor is causing the trouble. Note that if I simply include the Shared.fx code in the shaders I am using it, they build just fine.

Here is the shader I am sharing:

Shared.fx:
```
// Input parameters.
texture spriteBatchTexture;
sampler TextureSampler  : register(s0) = sampler_state
{
    Texture = <spriteBatchTexture>;
    MipFilter = Point;
    MagFilter = Point;
    MinFilter = Point;
    AddressU = Wrap;
    AddressV = Wrap;
};

float4x4 MatrixTransform : register(c0);

float2   ViewportSize;
float2   TextureSize;

int objectLightingTextureWidth;
int objectLightingTextureHeight;
float2 lightOffset;

float ignoreThreshold = 0.01;
int magicNumber = 4;

texture IgnoreTex;
sampler IgnoreSampler = sampler_state
{
    Texture = <IgnoreTex>;
    MipFilter = Point;
    MagFilter = Point;
    MinFilter = Point;
    AddressU = Wrap;
    AddressV = Wrap;
};

texture ObjectTexture;
sampler ObjectSampler = sampler_state
{
    Texture = <ObjectTexture>;
    MipFilter = Point;
    MagFilter = Point;
    MinFilter = Point;
    AddressU = Wrap;
    AddressV = Wrap;
};

texture BaseTexture;
sampler BaseSampler = sampler_state
{
    Texture = <BaseTexture>;
    MipFilter = Point;
    MagFilter = Point;
    MinFilter = Point;
    AddressU = Wrap;
    AddressV = Wrap;
};

texture BaseIgnoreTex;
sampler BaseIgnoreSampler = sampler_state
{
    Texture = <BaseIgnoreTex>;
    MipFilter = Point;
    MagFilter = Point;
    MinFilter = Point;
    AddressU = Wrap;
    AddressV = Wrap;
};

const static int NUM = 101;
int3 ignoreColors[NUM] = {
            int3(0,0,43),
			int3(0,7,59),
			int3(95,167,215)
};

struct VS_INPUT
{
	float4 position : POSITION0;
	float4 color    : COLOR0;
	float2 texCoord : TEXCOORD0;
};

struct VS_OUTPUT
{
	float4 position : POSITION0;
	float4 color    : COLOR0;
	float2 texCoord : TEXCOORD0;
	float2 lightCoord : TEXCOORD1;
	float4 worldPosition : TEXCOORD2;
};

struct PS_INPUT
{
    float4 color    : COLOR0;
	float2 texCoord : TEXCOORD0;
	float2 lightCoord : TEXCOORD1;
	float4 worldPosition : TEXCOORD2;
};


float2 TexCoords(float2 texCoord, float textureWidth, float textureHeight)
{
	// compute floating point stride for texture
	float step_x = 1./textureWidth;
	float step_y = 1./textureHeight;

	// compute texel array coordinates
	int target_x = texCoord.x * textureWidth;
	int target_y = texCoord.y * textureHeight;

	// round to values, such that they're multiples of step_x and step_y
	float2 texCoordNew;
	texCoordNew.x = target_x * step_x;
	texCoordNew.y = target_y * step_y;

	return texCoordNew;
}

VS_OUTPUT DummyVS(VS_INPUT input)
{
	VS_OUTPUT output = (VS_OUTPUT)0;
	return output;
}

technique Dummy
{
	pass Pass1
	{
#if SM4
		VertexShader = compile vs_4_0_level_9_1 DummyVS();
#else
		VertexShader = compile vs_3_0 DummyVS();
#endif
	}
}
```

Ambience.fx using the #include preprocessor:

```
#include "Shared.fx"

// Vertex shader for rendering sprites on Windows.
VS_OUTPUT SpriteVertexShader(VS_INPUT input)
{
	VS_OUTPUT output = (VS_OUTPUT)0;
	float4 position = input.position;
	
	output.worldPosition = position;
	output.lightCoord = float2((position.x + 32) / objectLightingTextureWidth, (position.y + 32) / objectLightingTextureHeight);

    // Apply the matrix transform.
    output.position = mul(position, MatrixTransform);
    
	// Half pixel offset for correct texel centering.
	output.position.xy -= 0.5;

	// Viewport adjustment.
	output.position.xy /= ViewportSize;
	output.position.xy *= float2(2, -2);
	output.position.xy -= float2(1, -1);

	// Compute the texture coordinate.
	output.texCoord = input.texCoord;
	
	// Pass on color
	output.color = input.color;
	
	return (output);
}

float4 PSAmbience(PS_INPUT input) : COLOR
{
	float4 lightBase = input.color;
	float4 tileBase = tex2Dlod(TextureSampler, float4(input.texCoord, 0, 0));

	float4 ret;
	bool found = false;
	int testx, testy, testz;
	
	testx = round(tileBase.r * 255);
	testy = round(tileBase.g * 255);
	testz = round(tileBase.b * 255);

	float2 lookupPos = float2(testx / 256.0, testy / 256.0);
	float4 lookupResult = tex2Dlod(IgnoreSampler, float4(lookupPos, 0, 0));

	int rTest = round(lookupResult.r * 255);
	int gTest = round(lookupResult.g * 255);
	int bTest = round(lookupResult.b * 255);
	int aTest = round(lookupResult.a * 255);

	if((rTest == testz && rTest != magicNumber)
		|| (gTest == testz && gTest != magicNumber)
		|| (bTest == testz && bTest != magicNumber)
		|| (aTest == testz && aTest != magicNumber))
	{
		// ignore color
		ret = tileBase;
	}
	else
	{
		// lighting
		ret = float4(2*tileBase.rgb*lightBase.rgb, tileBase.a);
	}
	
	//return ret;
	return float4(ret.rgb * ret.a, ret.a); // premultiplied alpha
}

technique Ambience
{
    pass Pass1
    {
#if SM4
		VertexShader = compile vs_4_0_level_9_1 SpriteVertexShader();
		PixelShader = compile ps_4_0_level_9_1 PSAmbience();
#else
		VertexShader = compile vs_3_0 SpriteVertexShader();
		PixelShader = compile ps_3_0 PSAmbience();
#endif
    }
}
```

**Comment by tomspilman** [comment] 2015-05-01 00:55
@tgjones - Is the issue @soenneker is having because the preprocessor isn't recursively being called on `#included` files?

**Comment by tgjones** [comment] 2015-05-01 13:09
The problem is that CppNet doesn't add a newline at the end of included files, so if there isn't already a newline, then this ends up happening:

``` c
...
technique Dummy
{
	pass Pass1
	{
		VertexShader = compile vs_4_0_level_9_1 DummyVS();
	}
}#line 2 "C:\\Users\\Tim\\Documents\\GitHub\\monogame-samples\\CascadedShadowMaps\\CascadedShadowMaps\\Content\\effects\\Ambient.fx"

VS_OUTPUT SpriteVertexShader(VS_INPUT input)
...
```

The `#` in the #line directive *must* be the first character on a line, so the HLSL compiler fails with a syntax error.

I'll have a look at what the proper fix is.

**Comment by tomspilman** [comment] 2015-05-02 00:16
> The  #  in the #line directive must be the first character on a line

Ah...   well something to add to our test case I guess.

Seems like the right fix should be within CppNet if it is the one opening and managing that file.

**Comment by tgjones** [comment] 2015-05-15 16:17
I have a commit 698f66e45ed2afc1ba7629230f1a70f47d798403 with a failing test for this issue. I've logged an issue on the CppNet repo - xtravar/CppNet/issues/3 - because it's not obvious where in CppNet the newline should be inserted. Hopefully I'll get an answer there, and then I can submit a PR to CppNet, and subsequently to MonoGame.
