### ISSUE TITLE
DrawInstancePrimitives not implemented

### ISSUE THREAD

**Issue by totallyeviljake** [mono/MonoGame#1246] opened 2013-01-28 19:09 UTC
See issue 1229. DrawInstancePrimitives is not implemented. Need some research on how this may be supported on other platforms. @tomspilman may know how to do this in DX.

**Comment by tgjones** [comment] 2015-02-02 14:43
@tomspilman I think this is a dupe of #913?

**Comment by KonajuGames** [comment] 2015-02-02 14:49
It is.  Closing.

**Closed by KonajuGames** 2015-02-02 14:49 UTC
