### ISSUE TITLE
DrawUserIndexPrimitives with int indices array parameter does not work, but it does with short.

### ISSUE THREAD

**Issue by stefanvalianu** [mono/MonoGame#1206] opened 2013-01-22 08:03 UTC
Basically, the code provided in this (http://www.riemers.net/eng/Tutorials/XNA/Csharp/Series1/Terrain_basics.php) tutorial does not produce the expected result. The culprit seems to be the particular overload of DrawUserIndexPrimitives.

Using an indices array of type int[] does not produce the expected result shown on the page.

Converting the indices array to type short[] fixes the problem.

All the code is provided in the linked page.

As an added bit of info, I am running on a 64-bit Windows 8 platform running the latest stable 3.0 (1/21/2013)

**Comment by tgjones** [comment] 2015-02-13 10:32
Dupe of #1039.

**Closed** 2015-02-13 13:39 UTC
