### ISSUE TITLE
Content pipeline showing wrong location and root node name (Windows)

### ISSUE THREAD

**Issue by simoneddeland** [mono/MonoGame#4186] opened 2015-10-19 09:19 UTC
When I create a new monogame project and open the MGCB file, the location of the MGCB file shown in the GUI is wrong (see attached image). The actual location of the file is what it should be, not the one shown in the pipeline GUI.

The root node is also shown with the name "CONTEN~1" instead of "Content", which I guess is related to the location name error.

I'm using swedish as my Windows language.

![pipeline location](https://cloud.githubusercontent.com/assets/12908966/10573848/b47174d8-7652-11e5-8d85-a96f3fe58b3d.png)

**Comment by KonajuGames** [comment] 2015-10-19 10:18
What you see there is technically correct, though not pretty.  It is the short name form of the path and filename that Windows provides for backwards compatibility with applications that only understand the old 8.3 path format.  `Content.mgcb` doesn't fit the 8.3 format so it its short name format is set to `CONTEN~1`.  Why it is using that format here, I'm not sure.  It might be something to do with the Swedish language and the localized names that Windows uses for its special folders such as `My Documents`, but I'm just guessing here.

**Comment by tomspilman** [comment] 2015-10-19 20:14
Looking at the properties window you can see 8.1 file names all thru out it.  Not sure why that is happening there.

@simoneddeland - What version of Windows are you running?

**Comment by simoneddeland** [comment] 2015-10-19 21:12
@tomspilman This was on my work computer, which is running Windows 8 (not 8.1). I just tried it on my home computer running Windows 10 with swedish localization, and the problem does not occur there, so maybe it has something to do with the OS.

**Comment by tomspilman** [comment] 2015-10-19 21:27
Hum... that is curious.  It must be some OS setting as i don't think Win8 out of the box would do that.

**Comment by StunGunStudios** [comment] 2015-10-20 02:18
I've definitely seen CONTEN~1 displayed before, though, unhelpfully, I don't recall the exact situation.

**Comment by energyuser** [comment] 2015-10-31 11:57
I can confirm having this issue on Windows 10 Pro.

**Comment by simoneddeland** [comment] 2015-11-26 10:31
Some new information: When I change the name of the root content node from "CONTEN~1" to "Content", the location is changed to display the correct location of the file. The file ending, however, is changed from .MGCB to .MGC, maybe another limitation of the older file system that seems to be used here.

**Comment by tomspilman** [comment] 2015-11-26 15:30
>  maybe another limitation of the older file system that seems to be used here.

It looks like you can create an NTFS partition on a Win8 machine that has 8.3 file naming enabled:

https://support.microsoft.com/en-us/kb/121007

Maybe this is all an error from how your company formatted the hard drive for Windows 8.

**Comment by simoneddeland** [comment] 2015-11-26 15:41
Is there an easy way for me to check if that is the case without disabling it?

**Comment by tomspilman** [comment] 2015-11-26 15:55
I have no clue... you will have to do some research and figure that out.

But this is all looking like it isn't a MonoGame bug but a setting on the OS level.

**Comment by energyuser** [comment] 2015-11-27 15:56
I can also confirm that renaming the file creates a .MGC extension instead of .MGCB...

**Comment by simoneddeland** [comment] 2015-11-30 09:31
It seems like you found part of the problem @tomspilman 

I disabled 8.3 file name creation as shown in the link you posted. This is what is shown in my content pipeline window now.

![image](https://cloud.githubusercontent.com/assets/12908966/11468048/d455ad8a-974c-11e5-9418-2f29f7cb3252.png)

The root node now has the correct name ("Content" instead of "CONTEN~1"). In the location label the directories are still not showing their correct name however, showing at least partly a 8.3 filename.

When renaming the name of the content root node in the pipeline tool, the file extension is correctly kept (renaming the node to "Content2" changed the file name to "Content2.MGCB" instead of "Content2.MGC").


I would however like to add that I can still add content in the pipeline tool when using 8.3 filenames and its working correctly, it's just annoying to look at.

**Comment by tomspilman** [comment] 2015-12-03 18:23
Looks like the issue is the new files/folders created when 8.3 file support is enabled.  Once the file/folder is created it is stuck in that crappy 8.3 format.

I think this can be closed now... since it is clearly not a MonoGame issue.

**Comment by nkast** [comment] 2015-12-17 00:03
I can duplicate this on Win8.1. Just add some spaces (more than one or two) in the middle of any .mgcb file and double click on it. A "mycontent - Copy.mgcb" will do too.
 When opening from the menu there is no problem.

Then i changed the open commnand in the registry from 
C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\Pipeline.exe %1
to:
C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\Pipeline.exe "%1" 
and it was fixed.

it has to be the line https://github.com/mono/MonoGame/blob/4912717a8a1c87b58a74700b29cdb8379eae28b2/Installers/Windows/MonoGame.nsi#L97

**Comment by tomspilman** [comment] 2015-12-17 00:11
@nkast - That seems like a good additional fix to a sort of similar issue.

**Comment by energyuser** [comment] 2015-12-17 16:08
@nkast So has this been merged into master? Or you changed your own PC's registry? And if so which key exactly?

**Comment by nkast** [comment] 2015-12-17 19:42
I just posted the PR, we will see.
For now you can test the resulting executable and provide feedback if it works for you.
Run the MonoGameSetup.exe from buildserver http://teamcity.monogame.net/viewLog.html?buildId=12581&buildTypeId=MonoGame_DevelopWin&tab=artifacts#!ossgocr

If you wish to go back to official current release 3.4 or a more recent develop release from 
http://www.monogame.net/downloads/ you can merge this small .reg file
https://onedrive.live.com/redir?resid=21955F536F871E02!85243&authkey=!AFIEibXpOwOOvuE&ithint=file%2creg

**Closed** 2015-12-17 20:05 UTC

**Comment by tomspilman** [comment] 2015-12-17 20:33
The fix is now merged.

**Comment by nkast** [comment] 2015-12-17 20:40
@simoneddeland You will soon be able to find the updated \develop installer at  http://www.monogame.net/downloads/ 
Thanks Tom.

**Comment by simoneddeland** [comment] 2015-12-17 21:17
@nkast  I'll try that once it's available, thanks!

**Comment by simoneddeland** [comment] 2015-12-18 11:35
@nkast @tomspilman The fix solved the problem I had as well, no more "CONTEN~1"
