### ISSUE TITLE
Remove old MonoGame.ContentPipeline

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#3390] opened 2015-01-13 23:02 UTC
With the new content pipeline in place it is finally time to kill off the old XNA MonoGame processors.

Everything in the folder...

  https://github.com/mono/MonoGame/tree/develop/MonoGame.ContentPipeline

... can be deleted.  

We also need to fix the build script to stop building it and the Windows installer to skip installing it.

**Comment by prollin** [comment] 2015-01-13 23:39
Could this be postponed for a bit? we are still using the old pipeline and unless nobody else is, are we sure the new pipeline is rock solid on all platforms? Some changes that were made to properly support 3d model seem too recent for such action no?

Not trying to be a showstopper here, just making sure we don't delete something still used by some devs when it can be simply marked as "legacy" and kept around until the new cross platform content pipeline matures.

**Comment by tomspilman** [comment] 2015-01-13 23:49
> Could this be postponed for a bit? we are still using the old pipeline and unless nobody else is

Could be if there is enough demand for it...  but i suspect few do.  All I seem to see is people avoiding use of the pipeline completely or just reusing XNA content without any MonoGame platform optimizations.

Maybe we should release an 3.3 version first with it then feel ok to remove it from develop?

Anyone else really need the old pipeline processors?


> just making sure we don't delete something still used by some devs when it can be simply marked as "legacy"

The problem with that is that we have to keep the legacy bits working.  It isn't like one couldn't get the assemblies for the old pipeline from the MonoGame 3.2 release or any older develop build from the TeamCity server.

**Comment by theZMan** [comment] 2015-01-13 23:59
>Maybe we should release an 3.3 version first with it then feel ok to remove it from develop?
Yep - we should release a 3.3 anyway.. its clear from the reddit thread the other day that if you don't make big public release announcements everyone thinks the project is dead.

**Comment by tomspilman** [comment] 2015-01-14 00:04
> its clear from the reddit thread the other day that if you don't make big public release announcements everyone thinks the project is dead.

I doubt anything we do will keep people from thinking it is dead.  They lump us in with XNA and Mono all the time...  if it isn't Unity or Unreal people generally don't pay attention.

**Comment by tgjones** [comment] 2015-01-14 01:14
> They lump us in with XNA and Mono all the time... if it isn't Unity or Unreal people generally don't pay attention.

Speaking as a relative outsider, I don't think that's true. Before jumping in a few weeks ago, I also wasn't sure about the state of the MonoGame project - no release since April, no news on the site since April, etc. But clearly, if people take the time to actually look on GitHub (as I now have), there is a huge amount of activity and progress. But not everyone has time to do that.

So I think releasing v3.3 is just what the project needs. I think (/ hope) you'll be surprised at how much support there is for an open source, community-driven, game framework for .NET.

**Comment by tomspilman** [comment] 2015-01-14 01:34
> no release since April, no news on the site since April, etc. 

When I setup the website I had hoped to have the news be a source for all XNA/MonoGame information with daily updates.  We looked for people to help contribute, but other than Simon no one has had the time to do that.

Lately I've been contemplating removing the old news blog all together.

Modern "news" for us is PRs info and Twitter...   if someone wants to write a tutorial most people do so on their own blogs which we retweet.  All other work would be better off being focused on the official docs.

I've been wanting to integrate a "change log" sort of like the JSIL site does...

  http://www.jsil.org/

Which automatically displays content from the GitHub feeds and put that up next to the twitter feed.

> I think (/ hope) you'll be surprised at how much support there is for an open source, community-driven, game framework for .NET.

I'm pretty jaded I guess...  I've been working on the project just about daily for 3 years now and I've been surprised how little support there has been.  This is why i so totally appreciate the new stuff @tgjones, @cra0zy, and @shqrdx have been contributing lately...  you're more rare than you think.

**Comment by Eversor** [comment] 2015-01-14 13:17
Count me in for the testing of a 3.3 release, i believe the community would really appreciate it.
Is the new content pipeline ready for a stable release? With some help i would love to dedicate some time to support the testing

**Comment by tomspilman** [comment] 2015-01-14 13:35
> Is the new content pipeline ready for a stable release?

Whatever is in the develop branch right now will be what is 3.3.  So ready or not... the new content pipeline is in the 3.3 release.

>  i would love to dedicate some time to support testing and debugging it.

Great!  We can always use more people testing.

Just grab the latest develop branch build from the website and test away.  Report any bugs you find here in the GitHub issues page.

**Comment by tgjones** [comment] 2015-01-14 14:05
> Lately I've been contemplating removing the old news blog all together.

I do think the news section has value - even if the only news items are for new MG versions, and links to MonoGame-related tutorials / games / YouTube videos around the web - basically what you already put on Twitter, but perhaps a more filtered version - I don't really know for sure, but I would guess that a lot of people still rely on project websites to give them a feel for the current status of a project.

> I've been wanting to integrate a "change log" sort of like the JSIL site does...

That's a great idea.

> I'm pretty jaded I guess... I've been working on the project just about daily for 3 years now and I've been surprised how little support there has been.

I'm sorry to hear that, although not terribly surprised - I know from experience on my own projects that "support" can be rather slippery. Still, v3.3 will be an awesome release, with the fantastic work done on the content pipeline and pipeline GUI, as well as a lot of other things I don't know about - if anything is going to get people excited (perhaps again, perhaps for the first time) about the project and generate some momentum, it's a new release.

**Comment by willmotil** [comment] 2015-01-14 16:38
unleash the kraken .... :)~

**Comment by cra0zy** [comment] 2015-01-14 18:46
I think the following should be done:
<ul>
<li>wait for the new xs addin to be done</li>
<li>wait for me to update linux installer for the new addin</li>
<li>release 3.3</li>
<li>remove old pipeline</li>
<li>add video and video player classes for everything</li>
<li>few months of time for changes and fixes</li>
<li>release 4.0</li>
<li>do the #3306</li>
</ul>

**Comment by Eversor** [comment] 2015-01-14 19:12
Wow, i've been using the latest pipeline for all day, and it feels really rock solid. 
There are a few reproducible crashes but nothing relevant. 
It feels like a new Xna personally... Awesome job to the team!

**Comment by tomspilman** [comment] 2015-01-14 19:22
> I think the following should be done

I agree with getting the last bits of the new installers in place before 3.3.

After 3.3 my plan is to go to a regular monthly release cycle.  3.4, 3.5, ... , 3.10, 3.11, 3.xx, etc.  No waiting for features or anything...  just the release is whatever is current in the develop branch.

We can make the major version updates when we feel like enough has changed to warrant one.

**Comment by tomspilman** [comment] 2015-01-14 19:23
@Eversor - Thanks!  Please report those crashes if you can reproduce them.

**Comment by danzel** [comment] 2015-01-14 19:28
Regular monthly release sounds awesome. This is what it seems like UE does and it will definitely make the project seem more alive :)

**Comment by Nezz** [comment] 2015-01-15 00:49
If only we had the time for making releases... :)

**Comment by tomspilman** [comment] 2015-01-15 00:52
> If only we had the time for making releases

That is the thing... we can't "make" a release.  No one has time to freeze a branch, run exhaustive tests, prepare release notes, and then release it.

Instead we should strive to always be in a release state.  That means develop is supposed to be stable and at any point we can make a release build of it.

**Comment by danzel** [comment] 2015-01-15 01:01
> Instead we should strive to always be in a release state. That means develop is supposed to be stable and at any point we can make a release build of it.

:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Eversor** [comment] 2015-01-15 08:38
This sound like a tittle Too good to be true...
 Despite the good Will and excellent capabilities of everyone thinking that is possible to avoid and foresee all the problems that even a small change can cause is illusion. 
That said if the idea is to make a release each month there is no other way.
The best option could be to process the bigger pulls one month before release, so people using source can test them out before release.

**Comment by tomspilman** [comment] 2015-01-15 09:15
> Despite the good Will and excellent capabilities of everyone thinking that is possible to avoid and foresee all the problems that even a small change can cause is illusion.

No one is expecting that releases are 100% bug free.  Unity has 100s of employees and at least $20M in investor funding... yet every Unity release has bugs too.

My goal is to ship frequently, collect bug reports, fix them, and ensure the bug doesn't reappear thru unit tests.  The first few monthly releases might be rough, but the more we ship and fix the more reliable MonoGame becomes.

More automated testing is the only way forward for us.  The sooner we start enforcing unit tests for all code changes the better.

**Comment by Nezz** [comment] 2015-01-15 11:22
We are always using some random state of develop as our base and rarely encounter bugs. And if we do, it's my job to fix them :) Frequent nuget releases would totally make sense for me.

I think that automated tests are a bit problematic for MonoGame because we can't expect all collaborators to start writing tests, so we would probably need a general integration test suite.

**Comment by Eversor** [comment] 2015-01-15 12:17
I tell you this because that's the reason i still keep 2012 releases in my company repository, i can't wait to be able to remove them.
Besides sometimes a broken build is not something that easy to fix, not everyone is a git/dx/openal/opengl guru... (currently i'm struggling with the wp8 effects that seem quite broken in develop branch)

**Comment by willmotil** [comment] 2015-01-15 19:51
my views are from the stand point of simplicity visibility clarity and practicality... as it stands 
when they decide to try it out they go here http://www.monogame.net/downloads/

what is really important on this page what is visible what we see
typically on a download page **its whats at the top**... as it should be
    MonoGame 3.2   
    MonoGame 3.0.1
    MonoGame 3.0
    MonoGame 3.0 Beta
    ect...
the top one MonoGame 3.2 people see it first at the top and look at this like this ... 

if the page is clear and simple then this is the Best / Newest  stable working version... 
but... its about a year or so old now :( 
this can give a person just checking up on the status the feeling that nothing has happened 
at least nothing major since last year including the sum of bug fix's and improvements
which we know is not true but first impressions are important and people do gleam info

So now another point id want to emphasize is practicality... 
what is it you expect yourself from a stable release ? well probably the same thing as anyone else
you don't expect it to be bug free 
just a relatively up to date version during a period of stable development 
as in "non crashing no majorly newly introduced bugs"
for all they care as long doesn't crash to desktop or introduce major new bugs from previous versions ... its the newest stable release

Clarity
"MonoGame 3.2 is the latest TOP pick on the download page" ... put those words in stereo
i imagine on a fancy commercial it would sound really cool
*but....*
**the fact is**
this is probably *no better* and maybe *much worse*, then if you were to randomly pick a nightly dev build just taken from any day of the last month and place it atop that 3.2 as stable release 3.3

which brings us back to **my point** 
practically the latest version appears to the average visitor over a year old 
we know its arguably not any better then today's or tomorrow's dev build 
it probably is obsolete to the point it should no longer be at the top of the page

clarity
you could post up from tonight's dev build on that dl page as 3.3 tommorow 
then pull the pipeline add fixs and post it next week as 4.0 
the numbers alone would all make more sense, and that for the user is their purpose
while we are programers we use our own programs these version and revision numbers 
may serve two masters the developers and the users at the same time

unless their is a note next to them stating the difference between 3.3 3.4 or 4.0
**new or revisiting people are just going to think the top link is the best period and click that**

**Comment by tomspilman** [comment] 2015-01-15 22:23
@Nezz 

>  we can't expect all collaborators to start writing tests

But we have to when it is reasonable.  We're not asking to write all the tests...  just a test that proves their change works correctly.  Hopefully after a while a new test won't be needed because we already have good coverage with existing tests.

Now there are harder cases...    music, sound, window management, input,...  these are very hard to create unit tests for in general.  Unless it is obvious how to make a test for these types of changes... we wouldn't force them to make one.

> so we would probably need a general integration test suite.

What specifically were you thinking about here?

**Comment by tomspilman** [comment] 2015-01-15 22:26
@willmotil 

> this is probably no better and maybe much worse, then 
> if you were to randomly pick a nightly dev build

I agree... just about any current nightly build is better than the current 3.2 release.  

This is why I want to get things setup where we can push a release easily and frequently.  We can then get into a regular release cycle.  This will all begin with 3.3 which I want to do soon.

**Comment by Nezz** [comment] 2015-01-16 00:05
>What specifically were you thinking about here?

For example: process a png into a Texture2D, load it, draw it to a given position using SpriteBatch then compare the end result to a sample. This would reveal problems in many modules, so if someone adds an XNB compression that doesn't quite work out then it would break a test, even if there are no tests targeting XNB compression

**Comment by tomspilman** [comment] 2015-01-16 00:53
> This would reveal problems in many modules

 I see...  yeah unit tests usually try to focus on one feature and not a whole pipeline.  However you can make bigger unit tests and we did with like the XML serialization.  I don't see a problem making bigger tests myself.

> even if there are no tests targeting XNB compression

This is the thing... we should have tests for that.  XNB compression is actually something we could easily unit test.

**Comment by Nezz** [comment] 2015-01-16 01:02
>This is the thing... we should have tests for that. XNB compression is actually something we could easily unit test.

Yes, I just couldnt come up with a better example :)

**Comment by tomspilman** [comment] 2015-01-16 01:03
> Yes, I just couldnt come up with a better example :)

I think your point is unexpected interactions between systems and things that are hard/impossible to unit test like audio.

**Comment by Nezz** [comment] 2015-01-16 01:06
Partially. In this case it's also useful that general cases show problems even if there is no specific unit test for a given feature.

**Comment by willmotil** [comment] 2015-01-18 16:10
i have a idea
maybe pull a nightly dev build and post it up as a "latest official unstable build" + the date of the build
if nothing is majorly wrong with it after enough people dl it and use it 
like say after a month or so just make it 3.3 

but if there is something majorly hosed put up a newer one and let it sit for a bit and simmer
rinse and repeat every six months or 4 months or so

i think everyone can agree that no release including all the ones posted up is perfect or final

unit tests are great and larger problem identification tests can quickly find differences and bugs
but they are also time consuming and as i said its been at least a year since last release 
and just about any nightly nowdays is far better then monogame was a year or even two ago
yet
MonoGame 3.2
MonoGame 3.0.1
:(

**Comment by Inverness** [comment] 2015-01-29 22:42
I'd just like to jump in and say that I previously thought the MonoGame was stagnating before seeing how much activity was being done in GitHub. I don't think the infrequent updates and news releases do a good job of letting people know that MonoGame is still being actively worked on and is something people can expect to be maintained in the future. Unless something is feature-complete, having a huge time between updates does not present an appealing picture for this kind of software.

I think a minor update every one or two months would be a good idea in the future.

**Comment by tomspilman** [comment] 2015-03-17 14:48
FYI...  i'll be merging https://github.com/mono/MonoGame/pull/3617 later today which will remove the old content processors.

**Comment by cra0zy** [comment] 2015-03-21 22:49
@tomspilman This can be closed.

**Closed** 2015-03-21 23:24 UTC
Labels: ContentPipeline, Maintenance
