### ISSUE TITLE
Content Pipeline does not open file

### ISSUE THREAD

**Issue by MGZero** [mono/MonoGame#4065] opened 2015-08-08 23:15 UTC
I'm not able to open an mgcb file in the content pipeline.  Opening the tool and going to file open yields a blank window.  This issue does not occur on my Windows 7 machine using the same file.

Windows 8.1
Monogame 3.4

![content pipeline bug](https://cloud.githubusercontent.com/assets/1524901/9152720/b1293c40-3e01-11e5-9920-2d5327fe2eb9.png)

**Comment by cra0zy** [comment] 2015-08-09 00:14
Duplicate of: #3230
PR #4043 resolves it


You can try out the patch from: http://teamcity.monogame.net/repository/download/MonoGame_DevelopWin/9327:id/Windows/MonoGameSetup.exe?guest=1

**Comment by MGZero** [comment] 2015-08-09 00:21
Nailed it, thanks!

**Comment by danzel** [comment] 2015-08-09 02:28
@MGZero please close this issue then :)

**Comment by tomspilman** [comment] 2015-08-09 04:29
@MGZero - Did the development EXE that @cra0zy linked fix the issue for you?  Did you test it?

**Comment by MGZero** [comment] 2015-08-09 13:54
Yes, I just forgot to close the issue last night.

**Closed** 2015-08-09 13:54 UTC
