### ISSUE TITLE
alcMacOSXMixerOutputRate issue on iOS9

### ISSUE THREAD

**Issue by rzaitov** [mono/MonoGame#4076] opened 2015-08-13 13:23 UTC
ctor of OpenALSoundController crashes on iOS9 device/simulator with 
> System.EntryPointNotFoundException: alcMacOSXMixerOutputRate

Here is the self-contained example:
https://github.com/xamarin/monotouch-samples/tree/master/BouncingGameCompleteiOS

Looks like there is no symbol for *alcMacOSXMixerOutputRate* on iOS9. Sample works fine on iOS8.

Also have a look at Apple's sample
https://developer.apple.com/library/mac/samplecode/OpenALExample/Listings/Scene_m.html#//apple_ref/doc/uid/DTS10003587-Scene_m-DontLinkElementID_10

```
typedef ALvoid  AL_APIENTRY (*alcMacOSXMixerOutputRateProcPtr) (const ALdouble value);
ALvoid  alcMacOSXMixerOutputRateProc(const ALdouble value)
{
    static  alcMacOSXMixerOutputRateProcPtr proc = NULL;
    
    if (proc == NULL) {
        proc = (alcMacOSXMixerOutputRateProcPtr) alcGetProcAddress(NULL, (const ALCchar*) "alcMacOSXMixerOutputRate");
    }
    
    if (proc)
        proc(value);
 
    return;
}
```

I think that we have to check existance of *alcMacOSXMixerOutputRate* symbol first before invoke alcMacOSXMixerOutputRate function

I believe that this is a crasher https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/OpenALSoundController.cs#L95

**Comment by davidjcaton** [comment] 2015-08-19 09:26
I have just started testing my (as yet unreleased) game on devices running iOS 9. The game runs perfectly well on iOS 8 but crashes on startup when launched on a device running the latest iOS 9 beta. 

Inspecting the crash logs I see that my app may be experiencing problems related to those noted here. I have only just started to triage the issue but stack trace in the log points suggests the issue is here:

Microsoft_Xna_Framework_Audio_OpenALSoundController_OpenSoundController + 148

I'm going to look at this over the next couple of days and will feedback anything of interest.

**Comment by davidjcaton** [comment] 2015-08-19 14:21
I've just noticed a [thread on the Cocos2d forums] (http://forum.cocos2d-objc.org/t/openal-gone-in-ios-9/17391/4) about OpenAL support being dropped in iOS 9. Reading through the comments and looking at the Apple developer forum it may be the case that OpenAL support is going to be deprecated (rather than dropped immediately).

I'm not sure if this has implications to how this issue might be resolved.

**Comment by KonajuGames** [comment] 2015-08-19 16:07
I have often entertained the idea of writing our own audio mixer and resampler in managed code, which I did (a simple version of) for the OUYA and SHIELD port of FistPuncher because building and using OpenAL on Android is not fun.  This forthcoming deprecation of OpenAL on iOS 9 gives further impetus for putting this plan into effect.

**Comment by davidjcaton** [comment] 2015-08-21 09:07
So, it would seem that @rzaitov correctly identified the problem.

I forked the Monogame source and built a version of Monogame.Framework.iOS with the call to alcMacOSXMixerOutputRate in OpenALSoundController.cs commented out. I can report that this appears to fix my crash problem on the iOS 9 simulator/device combinations I have tested against. Furthermore, commenting out this line does not appear to adversely affect music / sound effects in my game. 

I've also done a minimal amount of testing against iOS 8.4 and not noticed any problems caused by commenting out that call to alcMacOSXMixerOutputRate.

I hope this information is of use to anyone else having related problems.

**Comment by suilevap** [comment] 2015-08-26 15:56
Met the same problem, proposed changes helped.  Thanks!

**Comment by YARG** [comment] 2015-09-03 16:26
I've just done a build from the latest source  #3.5.0.543 (31 Aug 15 22:11) and commented out line 95 : 

alcMacOSXMixerOutputRate(PREFERRED_MIX_RATE);

and this fixed it for me and my iOS App now works as expected on iOS9 (Beta 5).  Thanks guys.

**Comment by prollin** [comment] 2015-09-03 17:18
Run into this issue as well but I believe this is because monogame needs to specified full path for p/invoke. More info [here](http://forums.xamarin.com/discussion/comment/131529/#Comment_131529).

**Comment by YARG** [comment] 2015-09-03 19:26
Hi prollin thanks for the post, as far as I understand you don't need to rebuild libs / components unless they use UICollectionView or load nibs https://developer.xamarin.com/guides/ios/platform_features/ios9/   

For me I did an app build using the latest and greatest Xamarin.iOS and MonoGame source and I had the same System.EntryPointNotFoundException: alcMacOSXMixerOutputRate exception.  I then uncommented the alcMacOSXMixerOutputRate(PREFERRED_MIX_RATE);  did a clean build and the app worked .. which made me very happy ;-)

**Comment by jonathanpeppers** [comment] 2015-09-14 14:30
FYI, we ran into this issue on the iOS 9 GM Seed.

Using @danzel 's change above, solves the issue. I'd say it's good to merge, as sounds are working fine in our game.

**Comment by YARG** [comment] 2015-09-14 14:46
Yep I agree with Jonathan, we tested with iOS 9 GM Seed this morning and the fix holds.  Green light from us ;-)

**Comment by prollin** [comment] 2015-09-14 20:24
@YARG i am not sure you understood my comment. While your fix might fix *your* problem, ``alcMacOSXMixerOutputRate`` might have an important role for others (someone with more experience with this part of MonoGame can jump in).
My suggestion was that the **root** cause of the issue might be the [p/invoke declaration](https://github.com/danzel/MonoGame/blob/cfa495ce71adf786028eba9c75b1464dc79eb71e/MonoGame.Framework/Audio/OpenALSoundController.cs#L522) using a relative path instead of a full path as pointed out by @migueldeicaza in the linked forum post.

**Comment by danzel** [comment] 2015-09-14 21:11
It looks like we are using an absolute path, right?
Is there a way to debug P/Invokes on iOS?
I'm not sure how we'd figure this one out, it could be that the lib is in another location and it was working due to luck on previous iOS versions.

**Comment by prollin** [comment] 2015-09-15 00:47
@danzel It looks like it indeed; my comment was only to make sure of it since this is not a part of the code I am familiar with.
I guess in the meantime it would be nice to track the importance of `alcMacOSXMixerOutputRate` on iOS to make sure it is ok to remove on that platform.

**Comment by danzel** [comment] 2015-09-15 01:37
Did a bit of searching.

Notes on what it does over [here](https://books.google.co.nz/books?id=QoxeAqTvevIC&pg=PA389&lpg=PA389&dq=alcMacOSXMixerOutputRate&source=bl&ots=fMOaO3QBk-&sig=gy4PPm2XDYQ0nkT2niGko_IBFnM&hl=en&sa=X&ved=0CB0Q6AEwAGoVChMIiOzL1On3xwIVCNumCh2Azwe2#v=onepage&q=alcMacOSXMixerOutputRate&f=false)

Looks like doom on iOS [used this method](https://git.spaceduck.org/bnied/doom-ios/raw/3bf2af22f381441faccb13652bcf992a43bb8eb5/code/iphone/.svn/text-base/iphone_sound.c.svn-base) to lower the mixer rate, there isn't any check that the symbol exists.
However that code [doesn't exist any more](https://github.com/id-Software/DOOM-iOS/blob/master/code/iphone/iphone_sound.c#L140-L150)

I'm not sure what the default mixer rate is... I'd guess 44.1k or 48k, but haven't found anything that says what.
I suspect we can get away without this, but maybe someone can find something I've missed.

**Comment by KonajuGames** [comment] 2015-09-15 01:50
I'm happy to remove the call to this function, as done in PR #4103.  There should be no need to alter the preferred mixing rate.  Sounds will still be played as normal, and the system will resample if required.  The only benefits of knowing the mixing rate is if all sound effects are provided at that rate to avoid the mixer having to resample prior to mixing, and we don't enforce any of that in the audio pipeline.

**Comment by KonajuGames** [comment] 2015-09-15 05:08
I have merged @danzel's PR.

**Closed** 2015-09-15 05:07 UTC

**Comment by Future-Soft** [comment] 2015-09-30 21:17
Hi,
I'm using Xamarin with Monogame to build xna games and I encountered the same issue on my games with ios9, this was after I updated my xamarin today (sept 30th) to the latest version and I noticed it also updated monogame so my question is, should this fix already be in the stable channel or not?
( I believe that in still 3.4.x version in nuget)

**Comment by KonajuGames** [comment] 2015-09-30 22:38
It is in the GitHub repo, but not in an officially released package.  That will happen in the 3.5 release soon.

**Comment by Future-Soft** [comment] 2015-10-01 05:19
Hmmm I tried using the dll from the latest build on teamcity but now I get an exception when loading font resource file (EOF exception) those resources were build using the 3.4 version I believe, was the file format changed? and if so why no backward compatibility?

**Comment by KonajuGames** [comment] 2015-10-01 05:24
I believe the texture content pipeline changes went in after 3.4.  Previously for iOS it used the DXT flag for PVR compressed textures.  Now PVR has its own flag.  Those XNB files will need to be recreated using the 3.5 content pipeline.
