### ISSUE TITLE
Compile Shaders from Linux

### ISSUE THREAD

**Issue by h3ll5ur7er** [mono/MonoGame#4313] opened 2015-12-11 07:22 UTC
Would be nice to be able to compile shaders using a linux(ubuntu) os. By now compilation fails with the following message:

System.NotImplementedException: The method or operation is not implemented.
  at Microsoft.Xna.Framework.Content.Pipeline.Processors.EffectProcessor.Process (Microsoft.Xna.Framework.Content.Pipeline.Graphics.EffectContent input, Microsoft.Xna.Framework.Content.Pipeline.ContentProcessorContext context) <0x40dee1e0 + 0x00017> in <filename unknown>:0 
  at Microsoft.Xna.Framework.Content.Pipeline.ContentProcessor`2[TInput,TOutput].Microsoft.Xna.Framework.Content.Pipeline.IContentProcessor.Process (System.Object input, Microsoft.Xna.Framework.Content.Pipeline.ContentProcessorContext context) <0x40dee0c0 + 0x00096> in <filename unknown>:0 
  at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent (MonoGame.Framework.Content.Pipeline.Builder.PipelineBuildEvent pipelineEvent) <0x40dec920 + 0x003cc> in <filename unknown>:0

**Comment by cra0zy** [comment] 2015-12-17 10:59
2mgfx tool is not implemented for non Windows platforms yet.

This is a duplicate of: #2167 and #3270

**Comment by tomspilman** [comment] 2016-01-18 21:47
Closing this in favor of https://github.com/mono/MonoGame/issues/2167.

**Closed by tomspilman** 2016-01-18 21:47 UTC

**Comment by Rombersoft** [comment] 2019-12-26 10:57
I have the same problem on linux now. MonoGame Pipeline Tool 3.8.0.848

**Comment by cra0zy** [comment] 2019-12-26 16:58
We don't support compiling shaders from Linux, as mentioned in the comments above.
