### ISSUE TITLE
NullReferenceException when trying to Add Existing Content

### ISSUE THREAD

**Issue by DMFirmy** [mono/MonoGame#4835] opened 2016-05-10 19:02 UTC
Using the latest dev build of the content pipeline tool, I get the following exception every time I attempt to add existing items to my content project. I have attempted this on multiple machines to confirm it is not simply some issue wtih my rig:

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Eto.WinForms.Forms.WindowsFileDialog`2.<SetFilters>m__0(FileDialogFilter f)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Eto.WinForms.Forms.WindowsFileDialog`2.SetFilters()
   at Eto.WinForms.Forms.WindowsFileDialog`2.ShowDialog(Window parent)
   at MonoGame.Tools.Pipeline.MainView.ChooseContentFile(String initialDirectory, List`1& files)
   at MonoGame.Tools.Pipeline.PipelineController.Include()
   at MonoGame.Tools.Pipeline.MainView.OnAddItemClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Pipeline
    Assembly Version: 3.6.0.312
    Win32 Version: 3.6.0.312
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/Pipeline.exe
----------------------------------------
Eto
    Assembly Version: 2.2.5954.40073
    Win32 Version: 2.2.5954.40073
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/Eto.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1075.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MonoGame.Framework
    Assembly Version: 3.6.0.312
    Win32 Version: 3.6.0.312
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/MonoGame.Framework.DLL
----------------------------------------
System.Threading
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll
----------------------------------------
System.Globalization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Globalization/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Globalization.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Extensions.dll
----------------------------------------
System.Reflection.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Reflection.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.Extensions.dll
----------------------------------------
System.Reflection
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Reflection/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.dll
----------------------------------------
Windows.ApplicationModel
    Assembly Version: 255.255.255.255
    Win32 Version: 
    CodeBase: file:///C:/Windows/system32/WinMetadata/Windows.ApplicationModel.winmd
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1073.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
Eto.WinForms
    Assembly Version: 2.2.5954.40499
    Win32 Version: 2.2.5954.40499
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/Eto.WinForms.DLL
----------------------------------------
System.Collections
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Linq.Expressions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.Expressions.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ComponentModel.dll
----------------------------------------
System.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MonoGame.Framework.Content.Pipeline
    Assembly Version: 3.6.0.312
    Win32 Version: 3.6.0.312
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/MonoGame.Framework.Content.Pipeline.DLL
----------------------------------------
SharpDX
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/SharpDX.DLL
----------------------------------------
SharpDX.MediaFoundation
    Assembly Version: 2.6.3.0
    Win32 Version: 2.6.3
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/SharpDX.MediaFoundation.DLL
----------------------------------------
CppNet
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/MSBuild/MonoGame/v3.0/Tools/CppNet.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

`

**Comment by tomspilman** [comment] 2016-05-10 19:04
@cra0zy - Looks like some issue with the dialog?

**Comment by cra0zy** [comment] 2016-05-10 19:09
Duplicate of #4780 

#4786 fixes it

**Comment by DMFirmy** [comment] 2016-05-10 19:36
Thanks for the quick reply. I downloaded the build package from here:
http://teamcity.monogame.net/viewLog.html?buildId=12315&buildTypeId=MonoGame_PackagingWindows&tab=artifacts&guest=1

Now I am having a different issue. I have an XML document with an extension of ".tilesheet", but whenever I select it in my Content Project I get a dialog that says "Object Reference not set to an instance of an object."

I have confirmed that the file was correctly copied to the content folder, but I am not able to set a processor for it.

**Comment by cra0zy** [comment] 2016-05-10 19:47
> Now I am having a different issue. I have an XML document with an extension of ".tilesheet", but whenever I select it in my Content Project I get a dialog that says "Object Reference not set to an instance of an object."
> 
> I have confirmed that the file was correctly copied to the content folder, but I am not able to set a processor for it.

Just looked at it, the reason why that error is occurring is because your references are broken and it can't find an importer/processor, will fix it shortly.

**Comment by DMFirmy** [comment] 2016-05-10 19:51
Upon a little further investigation, I figured out what the issue was and found a work-around. When the content got added to the project it didn't have a default importer or processor assigned. As a work-around manually edited the and added

/importer:XmlImporter
/processor:PassThroughProcessor

**Comment by cra0zy** [comment] 2016-05-10 20:05
Fixed in #4786, will take some time for installer to generate again.

**Comment by cra0zy** [comment] 2016-05-10 20:14
Grab it while it's hot: http://teamcity.monogame.net/viewLog.html?buildId=12697&buildTypeId=MonoGame_PackagingWindows&tab=artifacts&guest=1

**Comment by cra0zy** [comment] 2016-07-06 10:52
@tomspilman This has been fixed in #4786

**Closed** 2016-07-06 14:16 UTC
