### ISSUE TITLE
Fix DirectX backbuffer resize behavior

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4922] opened 2016-06-11 02:13 UTC
The resize behavior on the WindowsDX build is incorrect:

![munch](https://cloud.githubusercontent.com/assets/103522/15982524/03330b8e-2f50-11e6-93d3-6123f85d66f4.PNG)

The top image is the code under XNA, the middle is the new Desktop GL with SDL2, and the bottom is Windows DX.

What is happening is the Windows DX build is not resizing the back buffer to match the client area of the window.  You can see XNA and the GL version of MonoGame do this correctly.

I'm just setting `Window.AllowUserResizing = true;` in the `Game` constructor and using this to scale the scene to fit the window:

```
                var screenHeight = GraphicsDevice.PresentationParameters.BackBufferHeight;
                var screenWidth = GraphicsDevice.PresentationParameters.BackBufferWidth;
```

**Comment by nathanleroux** [comment] 2016-06-23 08:56
Pull https://github.com/mono/MonoGame/pull/4959 should take care of this problem, does so on my end.

**Comment by cra0zy** [comment] 2016-06-23 09:44
Duplicate of: https://github.com/mono/MonoGame/issues/4018

**Comment by willmotil** [comment] 2016-06-30 19:32
posted on this not long ago https://github.com/mono/MonoGame/issues/4841
 i think this was working previously but has been busted in 3.5 somewere in the last few months.

**Closed** 2016-07-07 16:14 UTC
Labels: DirectX, Help Wanted
