### ISSUE TITLE
GamePadCapabilities.HasLeftVibrationMotor / HasRightVibrationMotor  is wrong

### ISSUE THREAD

**Issue by Martin-Schultz** [mono/MonoGame#4395] opened 2016-01-05 23:28 UTC
Hi,

I am using the latest nuget package from the develop feed 3.5.0967.
My Xbox 360 GamePad has both vibration motors, but the GamePadCapabilities return false on the corresponding HasLeft/RightVibrationMotor properties.
However i can set the vibration for both motors and they work just fine.

Is this already fixed in the current head?

Thanks and appreciation

**Comment by tomspilman** [comment] 2016-01-05 23:31
It is probably being caused by this unnecessary `#if`:

https://github.com/mono/MonoGame/blob/628894d7e9a18821040ebdfd47a7892a7c077afd/MonoGame.Framework/Input/GamePad.XInput.cs#L130

@MichaelDePiazzi - Got time to fix that too?

**Comment by MichaelDePiazzi** [comment] 2016-01-06 01:54
@tomspilman Sure, I'll take a quick look at it.

**Comment by MichaelDePiazzi** [comment] 2016-01-06 02:45
Ok, this should be fixed now by PR #4396. It probably needs a test from someone else though. In particular, it would be great if someone could test this with an XInput controller which does not have vibration motors.

**Closed** 2016-01-15 20:30 UTC
