### ISSUE TITLE
WinDX SoundEffect/SoundEffectInstance stop playing after half of duration. (last MGdev)

### ISSUE THREAD

**Issue by 6thVenom** [mono/MonoGame#3507] opened 2015-02-09 13:13 UTC
I have this issue only on the WinDX (windows) version of my project, WinGL is playing fine.

Tried to use "windows8"/"windows",  "Mono wave"/"XNA wave", medium/best quality content build, it makes no difference.
Tracked for everything wrong in my code side, like a resume/stop, but nothing.

Could it be a SharpDX.Xaudio issue?

Thanks for any help.
Greg.

**Comment by KonajuGames** [comment] 2015-02-09 13:32
I'm using many sound effects in a Windows DirectX-based game with all audio
processed by the MonoGame content pipeline.  I haven't come across any of
the issues you describe.  Are you able to provide a sample project that
demonstrates the issue?​

**Comment by 6thVenom** [comment] 2015-02-09 18:56
@KonajuGames Hi!

I should mention i'm using Ms Visual Studio Community 2013 and the last develop branch of Monogame (and its dependencies) on a Windows 8.1 pro 64 bits machine since few weeks, and it fires me some content compilation errors about MojoShader 32 vs 64 bits, and a wrong MGFX shader version.

I manually downloaded Naudio.dlls dependency, as it was not include into the git zip.

I'll try to make something for you test as soon as possible, thanks.

**Comment by 6thVenom** [comment] 2015-02-09 21:07
Edit: Just discovered few hours ago the new "Monogame Pipeline" tool, wasn't aware of such a jewel... Maybe that'll solve my problems as i was able to compile on the same env without any warning/error.

Should definitively turn the spotlines over it!

I'll back to give you news about my sounds problem soon.

**Comment by danzel** [comment] 2015-02-10 00:14
Could you close this issue off then please @6thVenom  :)

**Comment by KakCAT** [comment] 2015-03-11 15:46
Hi,

I have a similar problem and unfortunately I can't use the MG content builder. Most sounds (probably all) stop just in the middle. 

I think the problem is with the variable loopLength used in CreateBuffers and read directly from the XNB in SoundEffect Reader. Multiplying its value by two makes the sound play correctly. Personally I think the description of the header is incorrect, being loopStart and loopLength not in bytes but in samples.

Using PlayLength as "0" when creating the AudioBuffer also fixes all the problems (this is the solution I applied temporaly) 


I also spotted something suspicious: "var bytesPerSample = 2 * _format.Channels;" which seem to accept only 16 bits samples. I checked my samples and they are 16-bit samples, so the problem is not there, but may give problems for users of 8-bit samples, although I don't know if this is possible with SharpDX or the new MG content manager.


I can provide a wav and an original XNA xnb if you need.


Thanks,
Kak

**Comment by tomspilman** [comment] 2015-03-11 18:56
> I can't use the MG content builder. Most sounds (probably all) stop just in the middle. 

Are you saying sound effect XNBs from the official XNA content pipeline will not play correctly?

@KonajuGames - This suggests we have a bug in the MG runtime here and that the MG pipeline is covering up for it.

**Comment by KakCAT** [comment] 2015-03-11 21:00
Hi @tomspilman 

yes, I'm sure.

I've uploaded the sample files here:
http://online.ru-zero.com/files/audio.zip

cheer1.wav being the source and cheer1.xnb the XNA-compiled file (using best compression) and cheer1-mgcb generated by MGCB (best compression too) 

Doing a binary composition, both XNB files are almost the same except for the final bytes (mainly loopLenght, which is set to 0 in MGCB and contains a value in XNA, and matches my temporal fix explained above)

**Comment by KonajuGames** [comment] 2015-03-12 04:13
I can have a look at this.

**Comment by KonajuGames** [comment] 2015-03-18 16:45
I'm working on this at the moment.  Should have a fix in the next day or so.

**Comment by KonajuGames** [comment] 2015-03-19 16:53
Fix in PR #3638

**Closed** 2015-03-20 01:24 UTC
