### ISSUE TITLE
VertexElementFormat.Short4 and .Color

### ISSUE THREAD

**Issue by pzgulyas** [mono/MonoGame#4414] opened 2016-01-12 06:34 UTC
`VertexElementFormat.Short4` and `VertexElementFormat.Color` doesn't pass through to shader correctly. Instead, they screw up the vertex input structure entirely, causing other members of the structure also become fancy.

These formats must be replaced by `Vector4` (when porting from XNA) to work correctly. At least for `Color`, the vertex declaration can be left defined as is, just the actual vertex buffer data must be passed as `Vector4`. For `Short4` such a test cannot be done, since that also differs in bit-representation from `Vector4`.

Platform is DirectX Windows.

**Comment by tomspilman** [comment] 2016-01-12 13:06
Hum... not sure the cause exactly.

Can you share some of your shader code and your vertex buffer setup code?

Ideally a simple test case that shows the error would help tremendously in identifying and fixing the bug.

**Comment by pzgulyas** [comment] 2016-01-12 13:56
C# code is [here](https://github.com/pzgulyas/OpenRails/blob/MonoGame/Source/RunActivity/Viewer3D/ParticleEmitter.cs#L179), the shader code is [here](https://github.com/pzgulyas/OpenRails/blob/MonoGame/Source/RunActivity/Content/ParticleEmitterShader.fx#L62)

**Comment by tomspilman** [comment] 2016-01-13 16:41
I don't see anything wrong just looking at that...  I assume this all runs on XNA 4.

We would need to make a simple test case out of this and dig into what is going on there.

**Comment by mgarstenauer** [comment] 2016-01-13 16:57
Your vertex elements are

    16 + 16 + 16 + 8 + 4 = 60 bytes.

But your vertex stride says:

    sizeof(float) * 12 + sizeof(short) * 4 + sizeof(float) * 4 = 72 bytes.

**Comment by tomspilman** [comment] 2016-01-13 17:11
> But your vertex stride says:

I totally didn't look at the stride!  Thanks for catching that @mgarstenauer !

It seems the mistake here was assuming that the color is 4 floats (`sizeof(float) * 4`) when really is 4 bytes.

That said i suspect this still exposes a MonoGame bug.  The VB is created like so:

```
            VertexDeclaration = new VertexDeclaration(ParticleVertex.VertexStride, ParticleVertex.VertexElements);
            VertexBuffer = new DynamicVertexBuffer(graphicsDevice, VertexDeclaration, MaxParticles * VerticiesPerParticle, BufferUsage.WriteOnly);
```

So the VB should have an extra 12 bytes at the end of each vertex.  Right?

Then when setting data on the VB:

```
                VertexBuffer.SetData(FirstNewParticle * ParticleVertex.VertexStride * VerticiesPerParticle, Vertices, FirstNewParticle * VerticiesPerParticle, numParticlesToAdd * VerticiesPerParticle, ParticleVertex.VertexStride, SetDataOptions.NoOverwrite);
```

The stride is again used....  I suspect our implementation of `VertexBuffer.SetData` isn't doing the slow copy of each vertex with the gap at the end.

Are you following what i'm getting at here @mgarstenauer ?

**Comment by mgarstenauer** [comment] 2016-01-13 18:16
@tomspilman Yeah, I see what you mean. But - just from a quick glance - the 'VertexBuffer.SetData' looks good.

The more general question I have is: The Direct3D 11 input layout is defined by the input elements (vertex elements), which is set [here](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/Vertices/InputLayoutCache.cs#L90). The vertex buffers are set [here](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsDevice.DirectX.cs#L1159). Does the input layout and the vertex stride need to match? Or is it allowed to have a bigger vertex stride (padding) in DirectX 11? Is this a valid use case? (I am not aware of any DX examples where the input layout does not match the vertex stride.)

**Comment by tomspilman** [comment] 2016-01-13 18:30
> Does the input layout and the vertex stride need to match? Or is it allowed to have a bigger vertex stride (padding) in DirectX 11?

My guess is that it is allowed by design, but I don't know for certain.  We would have to hack a DirectX sample to be sure.

If it is allowed then we must have some bug here to dig out.

**Comment by mgarstenauer** [comment] 2016-01-13 18:38
Oh, I checked the wrong path in `VertexBuffer.SetData`. The path for the dynamic VB ([here](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/Vertices/VertexBuffer.DirectX.cs#L132)) ignores the vertex stride! I guess this has not been tested with dynamic VBs.

**Comment by tomspilman** [comment] 2016-01-13 18:48
> The path for the dynamic VB (here) ignores the vertex stride! 

That looks to be the bug then!

**Comment by nkast** [comment] 2016-02-15 10:31
@mgarstenauer,
> Oh, I checked the wrong path in VertexBuffer.SetData. The path for the dynamic VB (here) ignores the vertex stride! I guess this has not been tested with dynamic VBs.

fix: https://github.com/mono/MonoGame/pull/4021

**Comment by mgarstenauer** [comment] 2016-02-15 12:27
@nkast: Nice work.

I recommend merging #4021.
I assume this PR was overlooked? Should have been merged a long time ago. ;)

**Comment by nkast** [comment] 2016-02-15 13:42
Yes the PR is a bit old.
I went through the open issues today and  realized it's the same bug you were talking about.

**Comment by KonajuGames** [comment] 2016-02-18 12:40
#4021 has been merged.  Closing this issue.

**Closed by KonajuGames** 2016-02-18 12:40 UTC
Labels: DirectX, Help Wanted
