### ISSUE TITLE
Installation of 3.0 Beta doesn't detect VS on Win8 so doesnt install templates

### ISSUE THREAD

**Issue by gbanfill** [mono/MonoGame#880] opened 2012-10-18 08:27 UTC
I Installed MonoGame 3.0 beta on a Windows 8 box. Both VS2012 and VS2010 installed (no MonoDevelop). Could not see templates in VS2012 or VS2010 after install (I assumed I'd unchecked by mistake).  VS2012 is installed in C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE

I uninstalled then reinstalled but kept the installer window open.

Complete log from installer window:
Output folder: C:\Program Files (x86)\MSBuild\MonoGame\v3.0
Extract: monogame.ico
Extract: MonoGameContentProcessors.dll
Extract: NAudio.WindowsMediaFormat.dll
Extract: NAudio.dll
Extract: PVRTexLibC.dll
Extract: SharpDX.D3DCompiler.dll
Extract: SharpDX.dll
Extract: lame_enc.dll
Extract: libmojoshader_32.dll
Extract: yeti.mmedia.dll
Extract: yeti.mp3.dll
Extract: yeti.wmfsdk.dll
Output folder: C:\Program Files (x86)\MSBuild\MonoGame\v3.0
Extract: MonoGame.ContentPipeline.targets
Extract: NAudio.WindowsMediaFormat.dll
Extract: NAudio.dll
Extract: SharpDX.D3DCompiler.dll
Extract: SharpDX.D3DCompiler.xml
Extract: SharpDX.DXGI.dll
Extract: SharpDX.DXGI.xml
Extract: SharpDX.Direct2D1.dll
Extract: SharpDX.Direct2D1.xml
Extract: SharpDX.Direct3D10.dll
Extract: SharpDX.Direct3D10.xml
Extract: SharpDX.Direct3D11.Effects.dll
Extract: SharpDX.Direct3D11.Effects.xml
Extract: SharpDX.Direct3D11.dll
Extract: SharpDX.Direct3D11.xml
Extract: SharpDX.Direct3D9.dll
Extract: SharpDX.Direct3D9.xml
Extract: SharpDX.DirectInput.dll
Extract: SharpDX.DirectInput.xml
Extract: SharpDX.DirectSound.dll
Extract: SharpDX.DirectSound.xml
Extract: SharpDX.MediaFoundation.dll
Extract: SharpDX.MediaFoundation.xml
Extract: SharpDX.RawInput.dll
Extract: SharpDX.RawInput.xml
Extract: SharpDX.XACT3.dll
Extract: SharpDX.XACT3.xml
Extract: SharpDX.XAudio2.dll
Extract: SharpDX.XAudio2.xml
Extract: SharpDX.XInput.dll
Extract: SharpDX.XInput.xml
Extract: SharpDX.dll
Extract: SharpDX.xml
Extract: sharpdx_direct3d11_1_effects_arm.dll
Extract: sharpdx_direct3d11_1_effects_x64.dll
Extract: sharpdx_direct3d11_1_effects_x86.dll
Extract: sharpdx_direct3d11_effects_x64.dll
Extract: sharpdx_direct3d11_effects_x86.dll
Extract: NAudio.xml
Extract: license.txt
Extract: 2MGFX.exe
Extract: PVRTexLib.dll
Extract: libmojoshader.dll
Extract: lame_enc.dll
Output folder: C:\Program Files (x86)\MonoGame\v3.0\Assemblies
Extract: Lidgren.Network.Android.dll
Extract: Lidgren.Network.Windows.dll
Extract: Lidgren.Network.dll
Extract: Lidgren.Network.Windows.xml
Extract: Lidgren.Network.XML
Extract: Lidgren.Network.Android.dll
Extract: Lidgren.Network.Windows.dll
Extract: Lidgren.Network.dll
Extract: MonoGame.Framework.Android.dll
Extract: MonoGame.Framework.Linux.dll
Extract: MonoGame.Framework.Windows.dll
Extract: OpenTK.dll
Extract: SharpDX.DXGI.dll
Extract: SharpDX.Direct2D1.dll
Extract: SharpDX.Direct3D11.dll
Extract: SharpDX.MediaFoundation.dll
Extract: SharpDX.XAudio2.dll
Extract: SharpDX.XInput.dll
Extract: SharpDX.dll
Extract: Tao.Sdl.dll
Extract: Lidgren.Network.Windows.xml
Extract: Lidgren.Network.xml
Extract: SharpDX.DXGI.xml
Extract: SharpDX.Direct2D1.xml
Extract: SharpDX.Direct3D11.xml
Extract: SharpDX.MediaFoundation.xml
Extract: SharpDX.XAudio2.xml
Extract: SharpDX.XInput.xml
Extract: SharpDX.xml
Extract: OpenTK.dll
Extract: OpenTK.dll.config
Extract: OpenTK_svnversion.txt
Extract: Tao.Sdl.dll
Extract: SDL.dll
Output folder: C:\Program Files (x86)\MonoGame\v3.0\Assemblies\Windows8
Extract: MonoGame.Framework.Windows8.dll
Extract: SharpDX.D3DCompiler.dll
Extract: SharpDX.DXGI.dll
Extract: SharpDX.Direct2D1.dll
Extract: SharpDX.Direct3D11.dll
Extract: SharpDX.MediaFoundation.dll
Extract: SharpDX.XAudio2.dll
Extract: SharpDX.XInput.dll
Extract: SharpDX.dll
Extract: SharpDX.D3DCompiler.xml
Extract: SharpDX.DXGI.xml
Extract: SharpDX.Direct2D1.xml
Extract: SharpDX.Direct3D11.xml
Extract: SharpDX.MediaFoundation.xml
Extract: SharpDX.XAudio2.xml
Extract: SharpDX.XInput.xml
Extract: SharpDX.xml
Output folder: C:\Program Files (x86)\MonoGame\v3.0
Created uninstaller: C:\Program Files (x86)\MonoGame\v3.0\uninstall.exe
Extract: oalinst.exe
Execute: C:\Program Files (x86)\MonoGame\v3.0\oalinst.exe
Output folder: C:\Program Files (x86)\MonoGame\v3.0
MonoDevelop Not Found.
Visual Studio 2010 not found
Visual Studio 2012 not found
Create folder: C:\Users\george\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\MonoGame
Create shortcut: C:\Users\george\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\MonoGame\Uninstall.lnk
Completed

**Comment by tgjones** [comment] 2015-02-13 10:27
This looks more like a VS bug than a MG bug - although perhaps it's worth a brief mention in the docs that if you have set a custom location for your documents folder, the MG templates won't work as expected.

**Comment by tgjones** [comment] 2015-02-13 10:30
Actually this a dupe of #1296 - that bug has more discussion about the problem. So I think this one can be closed.

**Closed** 2015-02-13 13:48 UTC
