### ISSUE TITLE
FX will not allow #include

### ISSUE THREAD

**Issue by DrSanjeep** [mono/MonoGame#3978] opened 2015-07-02 21:53 UTC
These errors compiling effects completely ruined my day

`Unexpected token on #include line`
...
`error X1500: syntax error : unexpected token '-'`

Builds if I process the includes myself
Line numbers on errors are way off even when I process the includes

**Comment by KonajuGames** [comment] 2015-07-03 00:37
Can you show the relevant part of the .fx file where the error occurs?

Line numbers being incorrect is a known issue and is being worked on.

**Comment by DrSanjeep** [comment] 2015-07-03 22:00
I found in one of my header files there was an include at the very end of the file with no carriage return. This results in `Unexpected token on #include line` or sometimes `Object reference not set to an instance of an object.` e.g. `#include "a/NormalMap.h"`

**Comment by DrSanjeep** [comment] 2015-07-03 22:59
#define FREAK_1 0
	#define FREAK_2 0

	#if FREAK_3 > 0
	#endif

	#include "EmptyFile.h"

	technique GranTechnique
	{
		pass P0
		{
			VertexShader = compile vs_4_0 VertexShader_1();
			PixelShader = compile ps_4_0 PixelShadeler_1();
		}
	}

**Comment by DrSanjeep** [comment] 2015-07-09 16:46
Is this fixed yet?

**Comment by tgjones** [comment] 2015-07-13 14:44
This looks like a dupe of #3853.

**Comment by tomspilman** [comment] 2015-07-13 17:16
@DrSanjeep - If you have time today test with the latest development build.  PR https://github.com/mono/MonoGame/pull/3999 should have fixed your issue.

**Comment by DrSanjeep** [comment] 2015-07-16 22:34
@tomspilman Yes thanks thats fixed

**Closed** 2015-07-16 22:47 UTC
