### ISSUE TITLE
[WindowsGL] multiple gamepad issues

### ISSUE THREAD

**Issue by bousquetm** [mono/MonoGame#4252] opened 2015-11-19 12:35 UTC
Hi, it seems that there are some issues with the GamePad class on WindowsGL:
- Even though the method IsConnected() returns true, all buttons and all tumbsticks are on their default state (ButtonState.Released & Vector2.Zero).
- If I unplug the pad then restart the game, the buttons and thumbsticks work well
- But the Dpad is still not recognized (all the Dpad buttons are set to ButtonState.Released)
- The Y axis of the thumbsticks points down instead of up
- The PacketNumber always returns 0

I have observed those issues on 2 different PCs (both on Windows 7) with 2 different classic XBox 360 controllers. Also those issues do not occur in a Windows DirectX project.

edit: forgot to mention that it was tested with Monogame 3.5.0.730.

**Comment by tomspilman** [comment] 2015-11-19 17:16
@cra0zy ?

**Comment by cra0zy** [comment] 2015-11-19 17:47
What is it returning as the name for the controller?

**Comment by bousquetm** [comment] 2015-11-19 18:01
How can I get the name of the controller ? I don't see any field 'Name'.

The GamePadCapabilities shows this:
GamePadType	Unknown
HasAButton	true
HasBackButton	true
HasBButton	true
HasBigButton	true
HasDPadDownButton	true
HasDPadLeftButton	true
HasDPadRightButton	true
HasDPadUpButton	true
HasLeftShoulderButton	true
HasLeftStickButton	true
HasLeftTrigger	true
HasLeftVibrationMotor	false
HasLeftXThumbStick	true
HasLeftYThumbStick	true
HasRightShoulderButton	true
HasRightStickButton	true
HasRightTrigger	true
HasRightVibrationMotor	false
HasRightXThumbStick	true
HasRightYThumbStick	true
HasStartButton	true
HasVoiceSupport	false
HasXButton	true
HasYButton	true
IsConnected	true

**Comment by cra0zy** [comment] 2015-11-19 18:17
Sorry, my bad, forgot to mention how to do it.

Do: OpenTK.Input.GamePad.GetName(index)

**Comment by bousquetm** [comment] 2015-11-19 18:21
it returns "XInput Controller".

**Comment by cra0zy** [comment] 2015-11-19 18:34
So, I don't have time to help out with this for the next 3 days, but long story short:

OpenTK uses this database file: https://github.com/opentk/opentk/blob/develop/Source/OpenTK/Input/GamePadConfigurationDatabase.cs

Probably line 78 is causing the issue, but it could also be line 74.

Can't remember where you get GUID from.

@Frassle Any easy gamepad mapping tool for OpenTK?

**Comment by bousquetm** [comment] 2015-11-20 15:18
no problem! I'll take a look this week-end if I have the time.

**Comment by bousquetm** [comment] 2016-01-03 14:53
Up! I think I found the problem with OpenTK. In https://github.com/opentk/opentk/blob/develop/Source/OpenTK/Platform/Windows/WinRawJoystick.cs, the DeviceCollection contains 3 items, the first two being "ghost" devices that have no buttons, no axis, and are not XInput devices. The 3rd one is the "real" gamepad.

After looking into the WinRawJoystick.RefreshDevices method, the ghost devices are flagged as RawInputDeviceType.HID, but the call to QueryDeviceCaps() fails with the error "[WinRawJoystick] HidProtocol.GetValueCaps() failed with 0" and still it returns true.  The inner loop is:

```C#
bool QueryDeviceCaps(Device stick)
{
	try
	{
		if (GetPreparsedData(stick.Handle, ref PreparsedData) &&
			GetDeviceCaps(stick, PreparsedData, out caps))
		{
			// stuff
		}
	}
	finally
	{
		Debug.Unindent();
	}

	return true;
}
```
But I think it should be:

```C#
bool QueryDeviceCaps(Device stick)
{
	try
	{
		if (GetPreparsedData(stick.Handle, ref PreparsedData) &&
			GetDeviceCaps(stick, PreparsedData, out caps))
		{
			// stuff
		}
		else
		{
			return false;
		}
	}
	finally
	{
		Debug.Unindent();
	}

	return true;
}
```

(I just added a 'return false')

Do you think I should create an issue directly in the OpenTK repo ?

Stay tuned for the issues with the Dpad and the Y axis!

**Comment by cra0zy** [comment] 2016-01-03 15:02
> Do you think I should create an issue directly in the OpenTK repo ?

Do it.

Also I found: https://github.com/opentk/opentk/issues/286 , maybe related?

**Comment by mrhelmut** [comment] 2016-01-04 12:11
I'm encountering issues with the Y axis, as well as opentk/opentk#286

@bousquetm definitely an OpenTK issue.

**Comment by cra0zy** [comment] 2016-01-04 12:26
> I'm encountering issues with the Y axis

Again, it's probably due to database having wrong info.

I made Guid public, https://github.com/opentk/opentk/pull/319/files, so you should be able to find which config is wrong from here: https://github.com/opentk/opentk/blob/develop/Source/OpenTK/Input/GamePadConfigurationDatabase.cs

Also MG doesn't have the newest version of OpenTK(https://github.com/MonoGame/MonoGame.Dependencies/pull/65), so that method is not available in OpenTK that MG is using,

**Comment by mrhelmut** [comment] 2016-01-04 12:41
Ok, I'll check the Guid and update the database.

**Comment by mrhelmut** [comment] 2016-01-04 14:21
The mapping looks to be OK, but there is no syntax for the mapping to know that an axis is inverted.
I only have Xbox360 gamepads to test that, but all Y's are inverted on all platforms.

I'll try that with PS3 & PS4 controllers to check if this is only linked to XInput controllers.

**Comment by cra0zy** [comment] 2016-01-04 14:39
Oh, now I see what's going on and why I didn't notice it...

**Comment by bousquetm** [comment] 2016-01-04 14:50
@cra0zy Ok I'm doing it.

The Y axis is a OpenTK issue, but I found a strange behavior in the Dpad handling on the Monogame side. When pressing the Dpad button down, 

```C#
GamePad.GetState(PlayerIndex.One).Dpad.Down 
```

returns Pressed, but 

```C#
GamePad.GetState(PlayerIndex.One).IsButtonDown(Buttons.DpadDown) 
```

return false. Maybe the bug lies in GetVirtualButtons() ? I'm nor sure.

**Comment by mrhelmut** [comment] 2016-01-04 15:14
You are right @bousquetm, DPad is not tested against in ```GetVirtualButtons()```. I'm going to submit a PR for that one.

**Comment by mrhelmut** [comment] 2016-01-04 16:14
I found another error, in OpenTK: the default value for both of the Triggers is 0.5f instead of 0.0f, and it doesn't change until Triggers are pressed. Only affects the SDL driver.

Still trying to figure out if this also affects non-Xbox360 gamepads, then I'll open an issue.

**Comment by cra0zy** [comment] 2016-01-04 16:17
> I found another error, in OpenTK: the default value for both of the Triggers is 0.5f instead of 0.0f, and it doesn't change until Triggers are pressed. Only affects the SDL driver.

Ha, unrelated, firefox has the same bug.... #4223, bow I am questioning is it a bug at all?

**Comment by mrhelmut** [comment] 2016-01-04 16:27
Don't know if it is a bug, but it doesn't match the XInput / XNA behavior.
In our game, players fire automatically if the triggers haven't been touched since app launch. This only happens when the SDL driver is used.

**Comment by mrhelmut** [comment] 2016-01-04 18:43
I have tested with a PS4 controller on Windows, the mapping is completely off and Y's are inverted. Still have to test with a PS3 controller, but it looks like the OpenTK mapping will require a lot a testing to get it right.

Before I take a look at this (inc. the Y axis), there are a couple of more important issues:
- opentk/opentk#286
- @bousquetm issues

> Even though the method IsConnected() returns true, all buttons and all tumbsticks are on their default state (ButtonState.Released & Vector2.Zero).
> If I unplug the pad then restart the game, the buttons and thumbsticks work well

I have encountered both of them, the latter seems strange because it works well on first launch, but after closing the game, the Xbox 360 controllers start blinking and don't work anymore (even though IsConnected is true) and I must unplug / replug them.

**Comment by mrhelmut** [comment] 2016-01-06 08:30
FYI, I have opened an issue regarding the mappings: [opentk/opentk#333](https://github.com/opentk/opentk/issues/333)

**Comment by mrhelmut** [comment] 2016-01-06 12:39
Update regarding the mapping.

We found out that the mapping may be correct, but the problem is that OpenTK returns different GUID's depending on the driver used (GLControl or SDL). And could also explain why keyboards are recognized as gamepads with the SDL driver.

**Comment by cra0zy** [comment] 2016-01-06 13:00
We could add: http://www.opentk.com/node/3685 to MonoGame to force OpenTK to not use SDL

**Comment by mrhelmut** [comment] 2016-01-06 13:46
I don't know. GamePad doesn't work on OS X without SDL. But if it was working, I would totally agree.

**Comment by cra0zy** [comment] 2016-01-06 13:51
Now the question is if it can't load OS X native driver, will it try using SDL one?

**Comment by cra0zy** [comment] 2016-01-06 13:51
Also #4397 ... I should have phrased it better.

**Comment by dellis1972** [comment] 2016-01-06 14:20
Which version of SDL is causing the problems? FNA doesn't seem to have this issue (or does it? )

**Comment by mrhelmut** [comment] 2016-01-06 14:25
I've been using these: [opentk/opentk-dependencies](https://github.com/opentk/opentk-dependencies)

**Comment by mrhelmut** [comment] 2016-01-07 20:13
I can confirm that all Y's are inverted on OpenTK compared to XInput, it's not just the 360 controller. They say that OpenTK is modeled against XInput, so I'm going to submit a PR on their side and not on MonoGame.
But before that, I'm going to work on the wrong PS3/PS4 mapping as well as the keyboard bug, and submit all PR at the same time in hope that they merge them fast enough.

**Comment by mrhelmut** [comment] 2016-01-08 10:59
I've narrowed down most the OpenTK issues, their HID driver had a couple problems.
[opentk/opentk#334](https://github.com/opentk/opentk/pull/334)
[opentk/opentk#335](https://github.com/opentk/opentk/pull/335)

When these PR get merged, Xbox 360, PS3 & PS4 controllers should work correctly and be mapped correctly on all platforms, including with the SDL2 driver on Windows.


Remaining problem (and big one): keyboard being recognized as 2 XInput devices. I'm investigating this. opentk/opentk#286

**Comment by cra0zy** [comment] 2016-01-08 11:02
> Remaining problem (and big one): keyboard being recognized as 2 XInput devices. I'm investigating this.

That one is only occurring with SDL backend, right?

**Comment by mrhelmut** [comment] 2016-01-08 11:03
No, it's their Windows HID driver messing up too.

**Comment by mrhelmut** [comment] 2016-01-08 12:21
Got it! I've updated the PR opentk/opentk#335

**Comment by mrhelmut** [comment] 2016-01-14 16:28
FYI, I've sent an e-mail to Frassle in hope to see these PR moving. This is starting to be critical for us since we have to maintain a lot of forks and we're soon releasing on MacOS & Linux.

**Comment by tomspilman** [comment] 2016-01-14 16:30
> I've sent an e-mail to Frassle in hope to see these PR moving.

Thanks... hopefully they will quickly correct this.

**Comment by SoundGoddess** [comment] 2016-05-22 18:26
Hrm I'm not sure if I should add this as a separate issue for this or not.  My Xbox compatible controller (Logitech Gamepad F310) works just fine with a WindowsDX project.  Everything is as expected.

But I take the same project and convert it to OpenGL and the trigger buttons do not work.

Here's the code in my Update method:
```
GamePadState controller = GamePad.GetState(PlayerIndex.One);
if (controller.IsButtonDown(Buttons.LeftTrigger)) camera.ZoomIn(deltaSeconds);
if (controller.IsButtonDown(Buttons.RightTrigger)) camera.ZoomOut(deltaSeconds);
```

**Comment by mrhelmut** [comment] 2016-05-23 09:00
I believe this is fixed in the latest develop branch (both the original issue and @SoundGoddess one). cc @tomspilman

**Closed** 2016-06-14 14:54 UTC
