### ISSUE TITLE
Couple issues with XAudio2 (corruption, freeze)

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4146] opened 2015-09-21 11:47 UTC
Hey there,

We are getting a few reports related to sfx which may be dependent to a few sound chip manufacturers.
Here are the issues, which may be unrelated, but we highly suspect that they are:

1. **Sound corruption**: after playing for an extended time (~1 hour), ```SoundEffect``` / ```SoundEffectInstance``` get corrupted. All sounds start to crackle a lot. ```MediaPlayer``` / ```Song``` are not affected (which seems normal since ```MediaPlayer``` uses MediaFoundation and not XAudio2).
2. **Freezes / stalls**: when sounds start to crackle, it is almost certain that playing a non pooled ```SoundEffectInstance``` (i.e. through ```SoundEffect.CreateInstance()```) will totally stall the game for several seconds. ```SoundEffect.Play()``` (i.e. pooled instances) doesn't stall the game.

I'm totally puzzled about these issues and we haven't been able to reproduce them internally which makes me think that they are related to specific sound chips and possibly driver issues.

It may also be only related to looped ```SoundEffectInstance```, because they tend to make the game stall more often/quickly.

I also don't know why only non-pooled instances are making the game to stall. I would suspect an hardware instance limit, but since the pool doesn't have a limit on Windows platforms, the problem would have been exposed way before any non-pooled instance is played.

I haven't found the time to test that against OpenAL.

**Comment by mrhelmut** [comment] 2015-09-22 06:57
We got more feedback about this issue and can confirm that it is not related to specific sound chip manufacturers.

**Comment by MichaelDePiazzi** [comment] 2015-09-23 02:30
@mrhelmut I totally forgot about this, but I think I had similar issues some time ago... I do remember that after an extended play session in my game (probably around an hour), that I started getting stuttering in game (and I think there was some funny audio playback issues like you mentioned also). I found that there was a bit of a memory leak going on, and it seemed to be related to sound effects being played. So as an experiment, I bypassed the MonoGame sound effect pool and implemented my own rudimentary version. This seemed to resolve the issue at the time and I haven't experienced it since. And since then I forgot about this and I should really look into what the hell was really going on there... :stuck_out_tongue:

**Comment by tomspilman** [comment] 2015-09-23 02:39
We'll be looking into this ourselves on a project soon too if no one gets to it first.

**Comment by KonajuGames** [comment] 2015-09-23 04:41
I've got a sound mixer implemented in pure C# that only requires one
streaming sound from the system (AudioTrack on Android, XAudio2 on Windows,
etc) that will use a lot fewer unmanaged system resources.  It still has
some work to be done (resampling on the fly from sound effect sample rate
to mixer rate is the next task), but once done it should be interesting to
see how it goes on larger projects with long play sessions.​

**Comment by tomspilman** [comment] 2015-09-23 04:49
> it should be interesting to see how it goes on larger projects with long play sessions.​

If it performs *really* well it might be a good consideration for use on all platforms just to avoid slight differences in the platform specific mixers.  The limit on simultaneous voices, what effects would be available, etc... would all be identical on all platforms then.

Again... only viable if the performance is really good even on lower end devices.

Still for now we need to fix whatever these XAudio issues are.

**Comment by KonajuGames** [comment] 2015-09-23 04:55
> If it performs really well it might be a good consideration for use on all platforms just to avoid slight differences in the platform specific mixers.

My plan is to try it on most, if not all, platforms.  There is very little platform-specific code in it.  One of the thoughts was that we have several cores going unused, even on mobile devices, that can be utilized for mixing and resampling without affecting the game update and rendering performance.  The core of the mixer has already been used on FistPuncher on OUYA and Android TV.

**Comment by tomspilman** [comment] 2015-09-23 05:00
> was that we have several cores going unused, even on mobile devices

Agreed... the mixing and even effects could be processed as tasks across unused cores.  This would further mitigate the cost of using managed code to do the work.  You can even go further by making the low level mixing use unsafe code to avoid array bounds checks which will be quite heavy for that type of code.

**Comment by KonajuGames** [comment] 2015-09-23 05:05
> You can even go further by making the low level mixing use unsafe code to avoid array bounds checks which will be quite heavy for that type of code.

Exactly.  Once it is proven robust, make it use unsafe array access to increase performance.  But this is now side-tracking this issue.  I'll keep working on this mixer, but these XAudio2 issues should be fixed in the meantime.

A memory leak sounds like some unmanaged resource is not being disposed correctly.

**Comment by mrhelmut** [comment] 2015-09-23 07:00
@KonajuGames Let me know once you have a branch ready to be tested, I'd be glad to help testing that mixer.

@MichaelDePiazzi Same here, if you have that pool system around.

I'm also wondering if pooling SoundEffectInstance from SoundEffect.CreateInstance() would be useful (right now there's a risk that they exceed the hardware limit). What do you think @KonajuGames @tomspilman ? I could setup a PR. Speaking of sound pool, mind reviewing this PR #4095 ?

Meanwhile, we tweaked our game to use a bit less fresh SoundEffectInstance's, it delays the problem but doesn't avoid it.

**Comment by tomspilman** [comment] 2015-09-23 07:05
> I'm also wondering if pooling SoundEffectInstance from SoundEffect.CreateInstance() would be useful 

I didn't do that when I implemented the pool because you don't know when an instance created via `SoundEffect.CreateInstance()` is truly done.  The user could call play at any time.

Anyway... more pooling just hides the issue.... we need to debug it and figure out the problem.  Step 1... we need to figure out a way to reproduce it.  I suggest starting with a dummy game that plays sounds over and over via `SoundEffect.CreateInstance()` and `SoundEffect.Play()`.   If the sounds are reasonably shorty you could play 1000s of times in a few minutes and hopefully repro the crash.

**Comment by KonajuGames** [comment] 2015-09-23 07:08
> I didn't do that when I implemented the pool because you don't know when an instance created via SoundEffect.CreateInstance() is truly done. The user could call play at any time.

I don't even know how you would pool those instances in the framework, because the game code is in total control of those.

**Comment by mrhelmut** [comment] 2015-09-23 07:09
My bad, I've been thinking too fast. ^^

We managed to get a computer exposing the problem, I'll try to come up with a minimal test.

**Comment by tomspilman** [comment] 2015-09-23 07:10
Fantastic!  If you get a test setup I can try to spend a little time investigating it.

**Comment by MichaelDePiazzi** [comment] 2015-09-23 07:19
@mrhelmut Actually, I just took a closer look at my code (it was almost a year ago that I had this issue).... I'm not actually doing any pooling at all! Whenever a sound is played, I create a new instance and add it to a list of active instances. I then regularly check that list for sounds that have stopped playing, and then remove them from the list and dispose them.... looking at it now, I'm actually surprised that it seems to work so well... :/

Anyway, glad that you've managed to get it reproducing now! Fingers crossed that it's a simple fix...

**Comment by mrhelmut** [comment] 2015-09-23 14:43
Can't reproduce the issue with a minimal test playing lots of sounds of all types (being pooled or not).  :-/
I let it run for a couple hours with no luck.

**Comment by tomspilman** [comment] 2015-09-23 21:10
Could it be mixing Song with SoundEffect?

The other case is that we have some sort of buffer overrun in another system that happens to corrupt XAudio data.

**Comment by mrhelmut** [comment] 2015-09-25 12:48
@tomspilman That was a good hint, adding a Song playing totally expose the issues!

Here's a test solution (mind your ears!) : https://www.dropbox.com/s/rdpcyyonpji31dj/XAudio2CorruptionTest.zip?dl=0

On our test computer, it starts to stall after a couple minutes and rapidly totally freeze.

I have no clue about the cause, I hope you guys can figure it out, we have about 25% of our users with this issue.

Also, take a look at the memory allocations.

P.S.: the sample re-create the effect instance on purpose, to make the issue show up more quickly.

cc @MichaelDePiazzi @KonajuGames

**Comment by tomspilman** [comment] 2015-09-25 15:45
> On our test computer, it starts to stall after a couple minutes and rapidly totally freeze.

It seems to do that here too.  It seems to start to pause as the memory usage goes up...  seems like a GC pause to me that gets worse and worse.

Investigating.

**Comment by tomspilman** [comment] 2015-09-25 15:51
So I've identified what it is....  we have a never ending buildup of `SharpDX.XAudio2.SourceVoice` instances.  Eventually there are so many it makes the GC stutter occur that is not recoverable.

Off to figure out why now.

**Comment by tomspilman** [comment] 2015-09-25 16:41
So contrary to what @mrhelmut found...   this is a bug in the sound effect instance pool:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffect.XAudio.cs#L186

If the instance came from the pool then `inst._voice` is not null.  We are simply overwriting the instance and never disposing it... resulting in leaked SharpDX resources, leading to eventually stalling the GC with lots of leaked object references.

@mrhelmut - This is my first quick pass at a fix.  Replace the `PlatformSetupInstance` in SoundEffect.XAudio.cs with this:

```
        private void PlatformSetupInstance(SoundEffectInstance inst)
        {
            var voice = inst._voice;

            if (voice != null)
            {
                var details = voice.VoiceDetails;

                if (details.InputSampleRate != _format.SampleRate ||
                    details.InputChannelCount != _format.Channels)
                {
                    voice.DestroyVoice();
                    voice.Dispose();
                    voice = null;
                }
            }

            if (voice == null && Device != null)
                voice = new SourceVoice(Device, _format, VoiceFlags.None, XAudio2.MaximumFrequencyRatio);

            inst._voice = voice;
        }
```

Give it a test and double check that this fixes the main issue here.

**Comment by tomspilman** [comment] 2015-09-25 16:46
Note this also shows a missing optimization in the pooling.  We could be trying to retrieve a previous instance with the same rate and channels as the sound we're about to play.  As long as we don't waste too much time in that search it could be a benefit to GC pressure and overall performance.

**Comment by tomspilman** [comment] 2015-09-25 17:08
@cra0zy - Looking at the OpenAL implementation I see that it too seems to leak `OALSoundBuffer` objects when a new `SoundEffectInstance` comes from the pool.  You can see here where it prepares sound instances:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffect.OpenAL.cs#L164

... where it calls InitializeSound which simply overwrites the instance with a new one:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffectInstance.OpenAL.cs#L61

... this should be either trying to reuse the `OALSoundBuffer` or disposing it like here:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffectInstance.OpenAL.cs#L263

Thoughts?

**Comment by tomspilman** [comment] 2015-09-25 17:10
@mrhelmut - Been running with my change for an hour under the memory profiler and I see no more memory leakage.  I suspect this is a good initial fix for this issue, but I really should get someone to test with their game first.

**Comment by mrhelmut** [comment] 2015-09-25 17:13
Oh! So it would have been the pooled instances initialization all along?
 I will test that on Monday for sure, I had to give back the test computer for the weekend.

If things go well, would you like me to push a PR? @tomspilman 
I'll try to come up with the optimization you suggested in a separate PR to give it some test.

**Comment by tomspilman** [comment] 2015-09-25 17:16
> Oh! So it would have been the pooled instances initialization all along?

I think the other instances and music running just made the problem appear much much quicker is all.

> I will test that on Monday for sure

Ok we can wait for that I suspect.


> would you like me to push a PR?

I think i'll submit a PR here in a minute as I have code working already and this is a pretty major leak.

**Comment by mrhelmut** [comment] 2015-09-25 17:26
Sounds great, thx. I'll test that asap. I'm also sending a test build of our project to a couple users who had the issue.

**Comment by cra0zy** [comment] 2015-09-25 17:38
Since we are filling in buffer here:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffect.OpenAL.cs#L167

putting a simple null check for initialization here:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffectInstance.OpenAL.cs#L64

should solve the problem, right?

**Comment by tomspilman** [comment] 2015-09-25 17:42
> should solve the problem, right?

Maybe...  I don't know how ` OALSoundBuffer` works myself.  Does `OALSoundBuffer` retain any state that is specific to the previous sound played?  Like the sample rate or number of channels or something?

**Comment by cra0zy** [comment] 2015-09-25 17:54
Pause state needs to get set, other than that, everything else gets set during the buffer filling .

Want me to setup a PR for OpenAL?

**Comment by tomspilman** [comment] 2015-09-25 18:04
I suspect my fix isn't fully correct...  think I need to test more than just the sample rate and channels.  I'm doing more testing now with a game sample.


> Want me to setup a PR for OpenAL?

Sure... we just need to be sure someone gives it a test on a game that uses a lot of `SoundEffect.Play()` calls.

**Comment by tomspilman** [comment] 2015-09-25 19:48
Ok... put up a PR with an improved test.  https://github.com/mono/MonoGame/pull/4155

**Closed** 2015-09-28 15:30 UTC

**Comment by troop53no** [comment] 2017-03-01 06:34
Has an actual fix to this issue been made yet?
