### ISSUE TITLE
[Pipeline,WIN] Latest Pipeline seems to be unable to convert Mp3 to SoundEffects

### ISSUE THREAD

**Issue by Eversor** [mono/MonoGame#3663] opened 2015-03-26 11:11 UTC
C:/Repos/DoomAndDestiny/XNA4/Content/Audio/SE/A_Team.mp3: error: Processor 'SoundEffectProcessor' had unexpected failure!
System.DivideByZeroException: Attempted to divide by zero.
   at Microsoft.Xna.Framework.Content.Pipeline.Audio.AudioContent.ConvertFormat(ConversionFormat formatType, ConversionQuality quality, String saveToFile) in c:\GitHub2\MonoGame\MonoGame.Framework.Content.Pipeline\Audio\AudioContent.cs:line 287
   at Microsoft.Xna.Framework.Content.Pipeline.Processors.SoundEffectProcessor.Process(AudioContent input, ContentProcessorContext context) in c:\GitHub2\MonoGame\MonoGame.Framework.Content.Pipeline\Processors\SoundEffectProcessor.cs:line 59
   at Microsoft.Xna.Framework.Content.Pipeline.ContentProcessor`2.Microsoft.Xna.Framework.Content.Pipeline.IContentProcessor.Process(Object input, ContentProcessorContext context) in c:\GitHub2\MonoGame\MonoGame.Framework.Content.Pipeline\ContentProcessor.cs:line 60
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent) in c:\GitHub2\MonoGame\MonoGame.Framework.Content.Pipeline\Builder\PipelineManager.cs:line 619
Build 0 succeeded, 1 failed.

**Comment by cra0zy** [comment] 2015-03-26 11:23
Duplicate of #3664

**Comment by KonajuGames** [comment] 2015-03-26 13:51
PR #3665 submitted.

**Closed** 2015-03-26 16:17 UTC
